# Generated by Django 5.1.2 on 2025-03-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='apporoach',
            new_name='approved',
        ),
    ]
